server.app/los.mobile/src/de/linogistix/mobile/processes/controller/MenuBean.java
/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.processes.controller;

import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import de.linogistix.mobile.common.gui.bean.BasicBackingBean;
import de.linogistix.mobile.common.gui.bean.BasicDialogBean;
import de.linogistix.mobile.common.system.JSFHelper;
import de.linogistix.mobileserver.processes.controller.ControllerFacade;
import de.linogistix.mobileserver.processes.controller.MobileFunction;


/**
 *
 * @author krane
 */
public class MenuBean extends BasicBackingBean {
	private static final Logger log = Logger.getLogger(MenuBean.class	.getName());

	
	private List<MenuAction> actions = null;
	private int numItems = 3;
	private int currentPage = 0;
	private ControllerFacade ctrlFacade;
	private boolean isInitialized = false;
	
    public MenuBean() {
    	super();
    	getLocale();
    	init();
    	isInitialized = true;
    }
    
    private void init() {
    	log.info("Init");
    	ctrlFacade = super.getStateless(ControllerFacade.class);

    	numItems = ctrlFacade.getMenuPageSize();
    	
    	actions = new ArrayList<MenuAction>();
    	
    	List<MobileFunction> fctList = ctrlFacade.getFunctions();
    	
    	for( MobileFunction fct : fctList ) {

			log.info("Add dialog " + fct.getClassName() );
			
    		BasicDialogBean dialog;
			try {
		        dialog = (BasicDialogBean) JSFHelper.getInstance().getSessionBeanForce( Class.forName(fct.getClassName()) );
			} catch (Throwable e) {
				log.error("Cannot instanciate dialog. Name="+fct.getClassName()+", Exception: " + e.getMessage(), e);
				continue;
			}
			if( dialog == null ) {
				log.error("Cannot instanciate dialog. Name="+fct.getClassName());
				continue;
			}
			
			dialog.init(fct.getArgs());
			
    		actions.add( new MenuAction( dialog.getTitle(), dialog.getNavigationKey() ) );
    	}
    	
    	
    	currentPage = 0;
    }

    
    /**
     * Just for the stupid picking dialog. It is not able to operate by itself.
     * Kill this method after building a stable picking dialog.
     */
    private void resetProcesses() {
    }
    public String getValue0() {
    	if( ! isInitialized ) {
    		init();
    	}
    	return getValue(0);
    }
    public String getValue1() {
    	return getValue(1);
    }
    public String getValue2() {
    	return getValue(2);
    }
    public String getValue3() {
    	return getValue(3);
    }
    public String getValue(int num) {
    	if(num >= numItems) {
    		return "";
    	}
    	int idx = (currentPage * numItems) + num;
    	return "" + ((actions.size() > idx) ? resolve(actions.get(idx).name) : "");
    }
    
    public String action0() {
    	return action(0);
    }
    public String action1() {
    	return action(1);
    }
    public String action2() {
    	return action(2);
    }
    public String action3() {
    	return action(3);
    }
    public String action(int num) {
    	resetProcesses();
    	int idx = (currentPage * numItems) + num;
    	return "" + ((actions.size() > idx) ? actions.get(idx).action : "");
    }
    
    public boolean getHasNextPage() {
    	int idx = (currentPage * numItems) + numItems;
    	return idx < actions.size();
    }
    
    public boolean getHasPrevPage() {
    	return currentPage > 0;
    }
    
    public String processNextPage() {
    	currentPage++;
    	return "";
    }

    public String processPrevPage() {
    	if( currentPage > 0 ) {
    		currentPage--;
    	}
    	return "";
    }
    
    public String processLogout(){
    	isInitialized = false;
        return "Logout";
    }

}


class MenuAction {
	String name;
	String action;
	
	MenuAction( String name, String action ) {
		this.name = name;
		this.action = action;
	}
}

server.app/los.mobile/src/de/linogistix/mobile/processes/picking/PickingMobileBean.java
/*
 * Copyright (c) 2011-2013 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.processes.picking;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

import javax.faces.event.ValueChangeEvent;
import javax.faces.model.SelectItem;

import org.apache.log4j.Logger;
import org.mywms.facade.FacadeException;
import org.mywms.model.Client;

import de.linogistix.los.model.State;
import de.linogistix.mobile.common.gui.bean.BasicDialogBean;
import de.linogistix.mobile.common.system.JSFHelper;
import de.linogistix.mobileserver.processes.picking.PickingMobileOrder;
import de.linogistix.mobileserver.processes.picking.PickingMobilePos;

/**
 * @author krane
 *
 */
public class PickingMobileBean extends BasicDialogBean {
	Logger log = Logger.getLogger(PickingMobileBean.class);


	// ***********************************************************************
	// Switches. Configured with system properties
	// ***********************************************************************
	
	protected Long selectedOrderId;
	protected List<SelectItem> orderSelectList;
	
	protected PickingMobileData data;
	protected List<String> serialList = null;
	
	protected String inputCode = "";
	protected String inputPrinter = "";
	protected BigDecimal amountTaken;
	protected BigDecimal amountRemaining;
	protected boolean locationCounted = false;
	protected String currentPrinter = null;
	protected Long currentId = null;

	protected boolean showClient = true;

	
	public PickingMobileBean() {
		super();
		
		data = new PickingMobileData();
		
		Client client = data.getDefaultClient();
		showClient = (client == null);
	}

	@Override
	public String getNavigationKey() {
		return getNavigationKey(PickingMobileNavigation.PICK_START);
	}

	@Override
	public String getTitle() {
		return resolve("TitlePickSingle");
	}

	String selClient;
	String selCustomerOrderNumber;
	String selCustomerOrderExternalNumber;
	String selNumPos;
	String selDate;
	String selStrategy;
	
	public void init() {
		log.debug("init");
		amountTaken = null;
		amountRemaining = null;
		locationCounted = false;
		inputCode = "";
		currentPrinter = null;
		orderSelectList = null;
		currentId = null;

		selClient = "";
		selCustomerOrderNumber = "";
		selCustomerOrderExternalNumber = "";
		selNumPos = "";
		selDate = "";
		selStrategy  ="";
		
		data.reset();
	}
	
	@Override
	public void init(String[] args) {
		super.init(args);
		init();
	}

	
	protected void initPos() {
		log.debug("Initialize position");
		inputCode = null;
		amountTaken = null;
		amountRemaining = null;
		locationCounted = false;
		currentId = null;
	}

	// ***********************************************************************
	// StartPicking.jsp
	// ***********************************************************************
	public String processStartPicking() {
    	log.debug("processStartPicking");
		init();
		try {
			data.resume(true);
		} catch (FacadeException e) {
			JSFHelper.getInstance().message( e.getLocalizedMessage() );
			return "";
		}

		if( data.getNumOrders()>0 ) {
			JSFHelper.getInstance().message( resolve("MsgRestore") );
			return getNavigationKey(PickingMobileNavigation.PICK_ORDER_SUMMARY);
		}
		return getNavigationKey(PickingMobileNavigation.PICK_ORDER_SELECT);
	}
	
	
	
	// ***********************************************************************
	// OrderSelect.jsp
	// ***********************************************************************
	protected List<SelectItem> getCalculatedPickingOrders(String code) {
		return data.getCalculatedPickingOrders( code, true, true );
	}
	public String processOrderSelect(){
		String code = inputCode == null ? "" : inputCode.trim();
		inputCode = "";
		
		if( code.length() > 0 ) {
			orderSelectList = getCalculatedPickingOrders( code );
			if( orderSelectList == null || orderSelectList .size() == 0 ) {
				orderSelectList = new ArrayList<SelectItem>();
				JSFHelper.getInstance().message( resolve("MsgNothingFound") );
				selectedOrderId=null;
				loadSelectedOrder();
				return "";
			}
			try{
				selectedOrderId = (Long)orderSelectList.get(0).getValue();
			} catch( Throwable t ) {
		    	log.error("Exception: "+t.getClass().getSimpleName()+", "+t.getMessage(), t);
			}
			if( orderSelectList.size() > 1 ) {
				loadSelectedOrder();
				return "";
			}
			orderSelectList = null;
		}

		if( selectedOrderId == null ) {
			JSFHelper.getInstance().message( resolve("MsgSelectEmpty") );
			orderSelectList = null;
			return "";
		}
		
		try {
			data.loadOrder(selectedOrderId);
			orderSelectList = null;
			if( isShowOrderInfo() ) {
				return getNavigationKey(PickingMobileNavigation.PICK_ORDER_INFO);
			}
			else {
				data.startPicking();
				if( !data.setFirstPick() ) {
					JSFHelper.getInstance().message( resolve("MsgNoPos") );
					return "";
				}
				return getNavigationKey(PickingMobileNavigation.PICK_PICKFROM);
			}
		} catch (FacadeException e) {
			orderSelectList = null;
			JSFHelper.getInstance().message( e.getLocalizedMessage(getUIViewRoot().getLocale()) );
			return "";
		}

		
	}
	
	public String processOrderSelectCancel() {
		try {
			data.removeAllOrders();
		} catch (FacadeException e) {
			JSFHelper.getInstance().message( e.getLocalizedMessage(getUIViewRoot().getLocale()) );
			return "";
		}
			
		init();
		return getNavigationKey(PickingMobileNavigation.PICK_MENU);
	}

	public List<SelectItem> getOrderList(){
		String logStr = "getOrderList ";

		if( orderSelectList == null ) {
			selectedOrderId = null;

			orderSelectList = getCalculatedPickingOrders( null );
			if( orderSelectList == null ) {
				orderSelectList = new ArrayList<SelectItem>();
			}
			if( orderSelectList.size() > 0 ) {
				try{
					selectedOrderId = (Long)orderSelectList.get(0).getValue();
				} catch( Throwable t ) {
			    	log.error("Exception: "+t.getClass().getSimpleName()+", "+t.getMessage(), t);
				}
			}
			loadSelectedOrder();
		}
		
		log.info(logStr+"Found "+orderSelectList.size()+" orders");
		return orderSelectList;
	}

	public void setSelectedOrder(String sel){
		selectedOrderId = null;
		try{
			selectedOrderId = Long.valueOf(sel);
		} catch( Throwable t ) {}
	}
	
	public String getSelectedOrder(){
		if( selectedOrderId == null ) {
			return null;
		}
		
		return selectedOrderId.toString();
	}
	
    public void orderSelectionChanged(ValueChangeEvent vce) {
    	String sel = (String)vce.getNewValue();
    	setSelectedOrder(sel);
    	loadSelectedOrder();
    }

    protected void loadSelectedOrder() {
    	if( selectedOrderId != null ) {
	    	PickingMobileOrder order = data.readOrder(selectedOrderId);
	    	selClient = order.clientNumber;
	    	selCustomerOrderNumber = order.customerOrderNumber;
	    	selCustomerOrderExternalNumber = order.customerOrderExternalNumber;
	    	selNumPos = String.valueOf(order.numPos);
	    	selDate = order.created;
	    	selStrategy = order.strategy;
    	}
    	else {
	    	selClient = "";
	    	selCustomerOrderNumber = "";
	    	selCustomerOrderExternalNumber = "";
	    	selNumPos = "";
	    	selDate = "";
	    	selStrategy = "";
    	}
    }
    
	// ***********************************************************************
	// PickToPrint.jsp
	// ***********************************************************************
	public String processPickToPrintSelect(){
		String logStr = "processPickToPrintSelect ";
		String code = inputPrinter == null ? "" : inputPrinter.trim();
		inputPrinter = "";

		log.debug(logStr+getTrace()+", input="+code);
		
		currentPrinter = (code.length()==0 ? null : code);

		try {
			data.printLabel( currentPrinter );
		} catch (FacadeException e) {
			JSFHelper.getInstance().message( e.getLocalizedMessage(getUIViewRoot().getLocale()) );
			return "";
		}

		return getNavigationKey(PickingMobileNavigation.PICK_PICKTO_TARGET);
	}
	
	public String processPickToPrintSkip(){
		String logStr = " processPickToPrintSkip";
		log.debug(logStr+getTrace());

		inputPrinter = "";
		currentPrinter = null;
		return getNavigationKey(PickingMobileNavigation.PICK_PICKTO_TARGET);
	}

	// ***********************************************************************
	// OrderSummary.jsp
	// ***********************************************************************
	public String processOrderSummary(){
		return processOrderInfo();
	}
	
	public String processOrderSummaryCancel(){
		return processOrderInfoCancel();
	}
	
	// ***********************************************************************
	// OrderInfo.jsp
	// ***********************************************************************
	public String processOrderInfo(){
		String logStr="processOrderInfo ";
		log.debug(logStr+getTrace());
		
		try {
			data.startPicking();
			
			if( data.setFirstPick() ) {
				return getNavigationKey(PickingMobileNavigation.PICK_PICKFROM);
			}
		} catch (FacadeException e) {
			JSFHelper.getInstance().message( e.getLocalizedMessage(getUIViewRoot().getLocale()) );
			return "";
		}
		
		log.error(logStr+"No pick found to process");
		JSFHelper.getInstance().message( resolve("MsgNoPos") );
		return processOrderInfoCancel();
	}
	
	public String processOrderInfoCancel(){
		String logStr = "processOrderInfoCancel ";
		log.debug(logStr+getTrace());

		inputCode = "";

		try {
			data.startPutAway();
			if( data.getCurrentPickTo() != null ) {
				return getNavigationKey(PickingMobileNavigation.PICK_PICKTO_TARGET);
			}
			data.removeAllOrders();
		} catch (FacadeException e) {
			JSFHelper.getInstance().message( e.getLocalizedMessage(getUIViewRoot().getLocale()) );
			return "";
		}
		
		init();
		
		return getNavigationKey(PickingMobileNavigation.PICK_ORDER_SELECT);
	}
	
	// ***********************************************************************
	// PickFrom.jsp
	// ***********************************************************************
	public String processPickFrom(){
		String logStr = "processPickFrom ";

server.app/los.mobile/srcServer/de/linogistix/mobileserver/processes/controller/ControllerFacadeBean.java
/*
 * Copyright (c) 2010 LinogistiX GmbH
 * 
 * www.linogistix.com
 * 
 * Project: myWMS-LOS
*/
package de.linogistix.mobileserver.processes.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Stateless;

@Stateless
public class ControllerFacadeBean implements ControllerFacade {

	@EJB
	private ManageMobile mobileService;
	
	
	public List<MobileFunction> getFunctions() {
		return mobileService.getFunctions();
	}
	
	
	public int getMenuPageSize() {
		return mobileService.getMenuPageSize();
	}
	
}

server.app/los.mobile/srcServer/de/linogistix/mobileserver/processes/controller/ManageMobileBean.java
/*
 * Copyright (c) 2010-2013 LinogistiX GmbH
 * 
 * www.linogistix.com
 * 
 * Project: myWMS-LOS
*/
package de.linogistix.mobileserver.processes.controller;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

import javax.ejb.Stateless;

import de.linogistix.los.inventory.model.LOSPickingOrder;
import de.linogistix.mobileserver.processes.picking.PickingMobileComparator;
import de.linogistix.mobileserver.processes.picking.PickingMobilePos;


public class ManageMobileBean implements ManageMobile {
	
	
	public List<MobileFunction> getFunctions() {
		List<MobileFunction> functionList = new ArrayList<MobileFunction>();
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.info.InfoBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.goodsreceipt.GoodsReceiptBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.storage.StorageBackingBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.gr_direct.GRDirectBean", "MODE_GOODS_RECEIPT") );
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.gr_direct.GRDirectBean", "MODE_MATERIAL") );
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.picking.PickingMobileBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.shipping.ShippingBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.replenish.ReplenishMobileBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.stocktaking.StockTakingBean"));
		
		return functionList;
	}
	

	public int getMenuPageSize() {
		return 3;
	}
	
	public Comparator<PickingMobilePos> getPickingComparator() {
		return new PickingMobileComparator(false);
	}
	
	public String getPickingSelectionText(LOSPickingOrder pickingOrder) {
		return pickingOrder.getNumber();
	}
}

server.app/los.mobile/WebContent/pages/processes/replenish/OrderCanceled.jsp
<%-- 
  Copyright (c) 2010 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
        <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    
    <body class="verticalscroll" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" onload="load()">
        <f:view locale="#{ReplenishBean.locale}">
            <f:loadBundle var="bundle" basename ="de.linogistix.mobile.processes.replenish.ReplenishBundle" /> 
            
            <h:form id="Form" styleClass="form" >
                <%-- Page Title--%>
                <p id="pHeader"class="pageheader">
                	<h:outputText id="pagetitle" value="#{bundle.TitleCanceled}" styleClass="pagetitle"/>
	                <h:graphicImage id="logo" url="/pics/logo.gif" styleClass="logo"/>
               	</p>
                
                <div class="space">
                    <h:messages id="messages"  styleClass="error"/> 
                    <table  width="100%" border="0" cellspacing="0">
                    	<colgroup>
							<col width="10%"/>
							<col width="90%"/>
						</colgroup>
                    	
                   		<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="clientLabel" value="#{bundle.LabelClient}:" styleClass="param" rendered="#{ReplenishBean.showClient}"/> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="clientData" value="#{ReplenishBean.clientNumber}" styleClass="label" rendered="#{ReplenishBean.showClient}"/>
                            </td>
                        </tr>
                    	<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="sourceLabel" value="#{bundle.LabelSourceLocation}:" styleClass="param"/> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="sourceData" value="#{ReplenishBean.sourceName}" styleClass="labelBold"/>
                            </td>
                        </tr>
                    	<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="ulLabel" value="#{bundle.LabelUnitLoad}:" styleClass="param" /> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="ulData" value="#{ReplenishBean.sourceUnitLoad}" styleClass="labelBold" />
                            </td>
                        </tr>
                        <tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="destinationLabel" value="#{bundle.LabelDestination}:" styleClass="param"/> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="destinationData" value="#{ReplenishBean.destinationName}" styleClass="label"/>
                            </td>
                        </tr>
                    </table>

				</div>
				
                <div class="space" style="padding-top:15px">
                   	<h:outputLabel id="numPosLabel" value="#{bundle.MsgOrderCanceled}" styleClass="labelBold"/> 
                </div>
                

                <%-- Command Buttons --%>
                <div class="buttonbar">  
                    <h:commandButton id="BUTTON_CONTINUE" 
	                				 value="#{bundle.ButtonContinue}" 
	                				 action="#{ReplenishBean.processOrderDone}" 
	                				 styleClass="commandButton"  />
                </div>
            </h:form>
        </f:view> 
        <script type="text/javascript">
            
            function load() {            
                setFocus();    
            }    
            
            function setFocus() {
                document.getElementById('Form:BUTTON_CONTINUE').focus();
            }    
            
        </script>
        
    </body>
</html>

server.app/los.mobile/WebContent/pages/processes/replenish/OrderSelect.jsp
<%-- 
  Copyright (c) 2010 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
        <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    
    <body class="verticalscroll" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" onload="load()">
        <f:view locale="#{ReplenishBean.locale}">	
            <f:loadBundle var="bundle" basename ="de.linogistix.mobile.processes.replenish.ReplenishBundle" /> 

            <h:form id="Form" styleClass="form" >

                <p id="pHeader" class="pageheader">
                	<h:outputText id="pagetitle" value="#{bundle.TitleSelect}" styleClass="pagetitle" />
	                <h:graphicImage id="logo" url="/pics/logo.gif" styleClass="logo"/>
                </p>
                
                <div class="space">
                    <h:messages id="messages" styleClass="error"/>

  
                    <table width="100%" border="0" cellspacing="0">
                        <tr>
                            <td>
                                <h:outputLabel value="Select order" styleClass="label"/>
                            </td>
                        </tr><tr>
                            <td>
                                <h:selectOneMenu id="orderComboBox" 
                                				onchange="this.form.submit();"
                                				valueChangeListener="#{ReplenishBean.valueChanged}"
                                                value="#{ReplenishBean.selectedOrder}" style="width:100%;" >
                                    <f:selectItems
                                        value="#{ReplenishBean.orderList}" />
                                </h:selectOneMenu>
                            </td>
                        </tr>
					</table>

                    <table  width="100%" border="0" cellspacing="0">
                    	<colgroup>
							<col width="10%"/>
							<col width="90%"/>
						</colgroup>
                        
                   		<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="clientLabel" value="#{bundle.LabelClient}:" styleClass="param" rendered="#{ReplenishBean.showClient}"/> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="clientData" value="#{ReplenishBean.clientNumber}" styleClass="label" rendered="#{ReplenishBean.showClient}"/>
                            </td>
                        </tr>
                    	<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="sourceLabel" value="#{bundle.LabelSource}:" styleClass="param"/> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="sourceData" value="#{ReplenishBean.sourceName}" styleClass="label"/>
                            </td>
                        </tr>
                    	<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="destinationLabel" value="#{bundle.LabelDestination}:" styleClass="param"/> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="destinationData" value="#{ReplenishBean.destinationName}" styleClass="label"/>
                            </td>
                        </tr>
                    	<tr>
                            <td nowrap="nowrap" style="padding-right:20px;padding-top:5px;">
                            	<h:outputLabel id="matLabel" value="#{bundle.LabelItemData}:" styleClass="param"/> 
                            </td>
                            <td nowrap="nowrap" style="padding-top:5px;">
                              	<h:outputLabel id="matData" value="#{ReplenishBean.itemNumber}" styleClass="label"/>
                            </td>
                        </tr>
                        <tr>
                            <td nowrap="nowrap" colspan="2" style="padding-right:20px; padding-left:20px; font-size:smaller;">
                               	<h:outputLabel id="matName" value="#{ReplenishBean.itemName}" />
                            </td>
                        </tr>
                        
					</table>
                        
                    <table width="100%" border="0" cellspacing="0" style="padding-top:15px;">
                        <tr>
                            <td>
                            	<h:outputLabel id="input1Label" value="#{bundle.LabelEnterCode}" styleClass="label" />
                            </td>
                        </tr><tr>
                            <td>
                               	<h:inputText id="input1" 
                             			 value="#{ReplenishBean.inputCode}" 
                             			 styleClass="input" /> 
                            </td>
                        </tr>
                    </table>
                    
                </div>
                                        
                <%-- Command Buttons --%>
                <div class="buttonbar">  
	                 <h:commandButton id="forwardButton" 
	                 				 value="#{bundle.ButtonContinue}" 
	                 				 action="#{ReplenishBean.processOrderSelect}" 
	                 				 styleClass="commandButton"  />
					&#160;
	                 <h:commandButton id="backButton" 
	                 				 value="#{bundle.ButtonMenu}" 
	                 				 action="#{ReplenishBean.processOrderSelectCancel}" 
	                 				 styleClass="commandButton" />
                </div>
            </h:form>
        </f:view> 
        <script type="text/javascript">
            
            function load() {            
                setFocus();    
            }    
            
            function setFocus() {
                document.getElementById('Form:input1').focus();
                document.getElementById('Form:input1').select();
            }    
            
        </script>
    </body>
</html>

server.app/los.mobile/WebContent/pages/processes/replenish/StartProcess.jsp
<%-- 
  Copyright (c) 2012 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
        <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    <f:view locale="#{ReplenishBean.locale}" >
        <f:loadBundle var="bundle" basename ="de.linogistix.mobile.processes.replenish.ReplenishBundle" /> 
        
        <body onLoad="document.getElementById('form:start').click();">
			<h:form id="form"> 
               	<h:commandButton id="start" 
	                			value="#{bundle.ButtonStart}" 
	                			action="#{ReplenishBean.processStartProcess}"
								styleClass="commandButton" />  
		    </h:form>
	    </body>
    </f:view>
</html>