server.app/los.mobile/src/de/linogistix/mobile/processes/controller/MenuBean.java
/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.processes.controller;

import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import de.linogistix.mobile.common.gui.bean.BasicBackingBean;
import de.linogistix.mobile.common.gui.bean.BasicDialogBean;
import de.linogistix.mobile.common.system.JSFHelper;
import de.linogistix.mobileserver.processes.controller.ControllerFacade;
import de.linogistix.mobileserver.processes.controller.MobileFunction;


/**
 *
 * @author krane
 */
public class MenuBean extends BasicBackingBean {
	private static final Logger log = Logger.getLogger(MenuBean.class	.getName());

	
	private List<MenuAction> actions = null;
	private int numItems = 3;
	private int currentPage = 0;
	private ControllerFacade ctrlFacade;
	private boolean isInitialized = false;
	
    public MenuBean() {
    	super();
    	getLocale();
    	init();
    	isInitialized = true;
    }
    
    private void init() {
    	log.info("Init");
    	ctrlFacade = super.getStateless(ControllerFacade.class);

    	numItems = ctrlFacade.getMenuPageSize();
    	
    	actions = new ArrayList<MenuAction>();
    	
    	List<MobileFunction> fctList = ctrlFacade.getFunctions();
    	
    	for( MobileFunction fct : fctList ) {

			log.info("Add dialog " + fct.getClassName() );
			
    		BasicDialogBean dialog;
			try {
		        dialog = (BasicDialogBean) JSFHelper.getInstance().getSessionBeanForce( Class.forName(fct.getClassName()) );
			} catch (Throwable e) {
				log.error("Cannot instanciate dialog. Name="+fct.getClassName()+", Exception: " + e.getMessage(), e);
				continue;
			}
			if( dialog == null ) {
				log.error("Cannot instanciate dialog. Name="+fct.getClassName());
				continue;
			}
			
			dialog.init(fct.getArgs());
			
    		actions.add( new MenuAction( dialog.getTitle(), dialog.getNavigationKey() ) );
    	}
    	
    	
    	currentPage = 0;
    }

    
    /**
     * Just for the stupid picking dialog. It is not able to operate by itself.
     * Kill this method after building a stable picking dialog.
     */
    private void resetProcesses() {
    }
    public String getValue0() {
    	if( ! isInitialized ) {
    		init();
    	}
    	return getValue(0);
    }
    public String getValue1() {
    	return getValue(1);
    }
    public String getValue2() {
    	return getValue(2);
    }
    public String getValue3() {
    	return getValue(3);
    }
    public String getValue(int num) {
    	if(num >= numItems) {
    		return "";
    	}
    	int idx = (currentPage * numItems) + num;
    	return "" + ((actions.size() > idx) ? resolve(actions.get(idx).name) : "");
    }
    
    public String action0() {
    	return action(0);
    }
    public String action1() {
    	return action(1);
    }
    public String action2() {
    	return action(2);
    }
    public String action3() {
    	return action(3);
    }
    public String action(int num) {
    	resetProcesses();
    	int idx = (currentPage * numItems) + num;
    	return "" + ((actions.size() > idx) ? actions.get(idx).action : "");
    }
    
    public boolean getHasNextPage() {
    	int idx = (currentPage * numItems) + numItems;
    	return idx < actions.size();
    }
    
    public boolean getHasPrevPage() {
    	return currentPage > 0;
    }
    
    public String processNextPage() {
    	currentPage++;
    	return "";
    }

    public String processPrevPage() {
    	if( currentPage > 0 ) {
    		currentPage--;
    	}
    	return "";
    }
    
    public String processLogout(){
    	isInitialized = false;
        return "Logout";
    }

}


class MenuAction {
	String name;
	String action;
	
	MenuAction( String name, String action ) {
		this.name = name;
		this.action = action;
	}
}

server.app/los.mobile/src/de/linogistix/mobile/processes/info/InfoBean.java
/*
 * Copyright (c) 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.processes.info;

import java.math.BigDecimal;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

import org.apache.log4j.Logger;
import org.mywms.globals.SerialNoRecordType;
import org.mywms.model.Client;

import de.linogistix.mobile.common.gui.bean.BasicDialogBean;
import de.linogistix.mobile.common.system.JSFHelper;
import de.linogistix.mobileserver.processes.info.InfoFacade;
import de.linogistix.mobileserver.processes.info.InfoItemDataTO;
import de.linogistix.mobileserver.processes.info.InfoLocationTO;
import de.linogistix.mobileserver.processes.info.InfoOrderTO;
import de.linogistix.mobileserver.processes.info.InfoStockUnitTO;
import de.linogistix.mobileserver.processes.info.InfoUnitLoadTO;

/**
 * @author krane
 *
 */
public class InfoBean extends BasicDialogBean {
	Logger log = Logger.getLogger(InfoBean.class);

	
	protected InfoFacade infoFacade;
	
	protected List<InfoUnitLoadTO> currentUnitLoadList = null;
	protected List<InfoStockUnitTO> currentStockUnitList = null;
	protected List<InfoOrderTO> currentOrderList = null;
	
	protected int currentUnitLoadIdx = -1;
	protected int currentStockUnitIdx = -1;
	protected int currentOrderIdx = -1;
	protected String lastState = "";
	
	
	protected InfoUnitLoadTO currentUnitLoadTO = null;
	protected InfoLocationTO currentLocationTO = null;
	protected InfoItemDataTO currentItemDataTO = null;
	protected InfoStockUnitTO currentStockUnitTO = null;
	protected InfoOrderTO currentOrderTO = null;
	
	protected String specialNavigationCode = null;
	
	protected String inputCode = "";
	protected boolean showClient = true;
	
	public InfoBean() {
		super();
		infoFacade = super.getStateless(InfoFacade.class);
		Client client = infoFacade.getDefaultClient();
		showClient = (client == null);
	}

	protected void init() {
		currentUnitLoadList = null;
		currentStockUnitList = null;
		currentOrderList = null;
		
		currentOrderList = null;
		
		currentUnitLoadIdx = -1;
		currentStockUnitIdx = -1;
		currentOrderIdx = -1;
		lastState = "";

		
		currentUnitLoadTO = null;
		currentLocationTO = null;
		currentItemDataTO = null;
		currentStockUnitTO = null;
		currentOrderTO = null;
		

	}
	
	@Override
	public String getNavigationKey() {
		return InfoNavigation.INFO_ENTER_CODE.name();
	}

	@Override
	public String getTitle() {
		return resolve("TitleInfo");
	}
	
	public String processStart() {
		
		if( specialNavigationCode != null ) {
			log.info("Navigate to special target: "+specialNavigationCode);
			String code = specialNavigationCode;
			specialNavigationCode = null;
			return code;
		}
		
		return InfoNavigation.INFO_ENTER_CODE.toString();
	}
	
	
	// ***********************************************************************
	// EnterCode.jsp
	// ***********************************************************************
	public String processEnterCode() {
		String code = inputCode == null ? "" : inputCode.trim();
		inputCode = "";

		init();
		if( code.length() == 0 ) {
			JSFHelper.getInstance().message( resolve("MsgEnterCode") );
			return InfoNavigation.INFO_ENTER_CODE.toString();
		}
		
		log.info("Search for code="+code);
		
		currentUnitLoadTO = infoFacade.readUnitLoad(code);
		currentLocationTO = infoFacade.readLocation(code);
		currentItemDataTO = infoFacade.readItemData(code);
		log.info("Found UL="+(currentUnitLoadTO!=null)+", Loc="+(currentLocationTO!=null)+", Item="+(currentItemDataTO!=null));
		
		

		int anzType = 0;
		if( currentUnitLoadTO != null )
			anzType ++;
		if( currentLocationTO != null )
			anzType ++;
		if( currentItemDataTO != null )
			anzType ++;
		
		if( currentUnitLoadTO != null && currentLocationTO != null ) {
			return getLocationPage();
		}
		else if( anzType > 1 ) {
			return InfoNavigation.INFO_SELECT_TYPE.toString();
		}
		else if( currentUnitLoadTO != null ) {
			return getUnitLoadPage();
		}
		else if( currentLocationTO != null ) {
			return getLocationPage();
		}
		else if( currentItemDataTO != null ) {
			return InfoNavigation.INFO_SHOW_ITEMDATA.toString();
		}
		else {
			JSFHelper.getInstance().message( resolve("MsgNothingFound") );
			return InfoNavigation.INFO_ENTER_CODE.toString();
		}
		
	}
	
	public String processEnterCodeCancel() {
		init();
		return InfoNavigation.INFO_BACK_TO_MENU.toString();
	}

	
	
	
	// ***********************************************************************
	// SelectType.jsp
	// ***********************************************************************
	public String processSelectUnitLoad() {
		return getUnitLoadPage();
	}

	public String processSelectItemData() {
		return InfoNavigation.INFO_SHOW_ITEMDATA.toString();
	}

	public String processSelectLocation() {
		return getLocationPage();
	}
	
	public String processSelectCancel() {
		init();
		return processStart();
	}

	public boolean isUnitLoadSelected() {
		return currentUnitLoadTO != null;
	}
	
	public boolean isLocationSelected() {
		return currentLocationTO != null;
	}
	
	public boolean isItemDataSelected() {
		return currentItemDataTO != null;
	}

	
	
	// ***********************************************************************
	// ShowUnitLoad.jsp
	// ***********************************************************************
	public String processUnitLoadUnitLoad() {
		return InfoNavigation.INFO_SHOW_UNITLOAD.name();
	}
	
	public String processUnitLoadStockUnit() {
		if( currentUnitLoadTO == null ) {
			JSFHelper.getInstance().message( resolve("MsgUlNotSelected") );
			return "";
		}
		currentStockUnitList = currentUnitLoadTO.getStockUnitList();
		if( currentStockUnitList == null || currentStockUnitList.size() <= 0 ) {
			return "";
		}
		currentStockUnitIdx = 0;
		currentStockUnitTO = currentStockUnitList.get(0);
		
		return InfoNavigation.INFO_SHOW_STOCKUNIT.toString();
	}
	
	public String processUnitLoadOrder() {
		if( currentUnitLoadTO == null ) {
			JSFHelper.getInstance().message( resolve("MsgUlNotSelected") );
			return "";
		}
		lastState = InfoNavigation.INFO_SHOW_UNITLOAD.name();
		
		if( currentUnitLoadTO.getPickList().size() > 0 ) {
			currentOrderList = currentUnitLoadTO.getPickList();
		}
		else if( currentUnitLoadTO.getOrderList().size() > 0 ) {
			currentOrderList = currentUnitLoadTO.getOrderList();
		}
		else {
			return "";
		}
		currentOrderIdx = 0;
		currentOrderTO = currentOrderList.get(0);
		
		return InfoNavigation.INFO_SHOW_ORDER.toString();
	}
	
	public String processUnitLoadStockOrder() {
		if( currentUnitLoadTO == null ) {
			JSFHelper.getInstance().message( resolve("MsgUlNotSelected") );
			return "";
		}
		lastState = InfoNavigation.INFO_SHOW_UNITLOAD_STOCK.name();
		
		if( currentUnitLoadTO.getPickList().size() > 0 ) {
			currentOrderList = currentUnitLoadTO.getPickList();
		}
		else if( currentUnitLoadTO.getOrderList().size() > 0 ) {
			currentOrderList = currentUnitLoadTO.getOrderList();
		}
		else {
			return "";
		}
		currentOrderIdx = 0;
		currentOrderTO = currentOrderList.get(0);
		
		return InfoNavigation.INFO_SHOW_ORDER.toString();
	}
	
	public String processUnitLoadLocation() {
		if( currentUnitLoadTO == null ) {
			JSFHelper.getInstance().message( resolve("MsgUlNotSelected") );
			return "";
		}
		String locationName = currentUnitLoadTO.getLocationName();
		selectLocation( locationName );
		
		return InfoNavigation.INFO_SHOW_LOCATION.toString();
	}
	
	public String processUnitLoadNext() {
		if( currentUnitLoadList == null || currentUnitLoadIdx >= currentUnitLoadList.size()-1 ) {
			JSFHelper.getInstance().message( resolve("MsgEndOfList") );
			return getUnitLoadPage();
		}
		
		currentUnitLoadIdx++;
		
		if( currentUnitLoadIdx >= currentUnitLoadList.size() || currentUnitLoadIdx < 0 ) {
			JSFHelper.getInstance().message( resolve("MsgPosNotSelected") );
			return getUnitLoadPage();
		}
		
		currentUnitLoadTO = currentUnitLoadList.get(currentUnitLoadIdx);
		
		return getUnitLoadPage();
	}
	
	public String processUnitLoadPrev() {
		if( currentUnitLoadIdx <= 0 ) {
			JSFHelper.getInstance().message( resolve("MsgEndOfList") );
			return getUnitLoadPage();
		}
		
		currentUnitLoadIdx --;
		
		if( currentStockUnitIdx >= currentUnitLoadList.size() || currentUnitLoadIdx < 0 ) {
			JSFHelper.getInstance().message( resolve("MsgPosNotSelected") );
			return getUnitLoadPage();
		}

		currentUnitLoadTO = currentUnitLoadList.get(currentUnitLoadIdx);
		
		return getUnitLoadPage();
	}

	protected String getUnitLoadPage() {
		if( currentUnitLoadTO == null ) {
			JSFHelper.getInstance().message( resolve("MsgUlNotSelected") );
			return "";
		}
		if( currentUnitLoadTO.getStockUnitList().size() == 1 ) {
			currentStockUnitTO = currentUnitLoadTO.getStockUnitList().get(0);
			return InfoNavigation.INFO_SHOW_UNITLOAD_STOCK.toString();
		}
		else {
			return InfoNavigation.INFO_SHOW_UNITLOAD.toString();
		}
	}
	
	public boolean isUnitLoadHasPrev() {
		if( currentUnitLoadList == null || currentUnitLoadList.size() < 2 ) {
			return false;
		}
		return currentUnitLoadIdx > 0;
	}
	
	public boolean isUnitLoadHasNext() {
		if( currentUnitLoadList == null || currentUnitLoadList.size() < 2 ) {
			return false;
		}

		return currentUnitLoadIdx < (currentUnitLoadList.size()-1);
	}

	public boolean isUnitLoadHasOrderContent() {
		if( currentUnitLoadTO == null ) {
			return false;
		}

		return (currentUnitLoadTO.getOrderList().size() > 0 || currentUnitLoadTO.getPickList().size() > 0);
	}

	public boolean isUnitLoadHasContent() {
		return currentUnitLoadTO != null && currentUnitLoadTO.getStockUnitList().size() > 0;
	}

	public boolean isShowUnitLoadBack() {
		if( currentUnitLoadList != null && currentUnitLoadList.size() > 1 ) {
			return false;
		}
		return ( currentStockUnitTO != null );
	}
	
	// ***********************************************************************
	// ShowStockUnit.jsp
	// ***********************************************************************
	public String processStockUnitUnitLoad() {

server.app/los.mobile/srcServer/de/linogistix/mobileserver/processes/controller/ControllerFacadeBean.java
/*
 * Copyright (c) 2010 LinogistiX GmbH
 * 
 * www.linogistix.com
 * 
 * Project: myWMS-LOS
*/
package de.linogistix.mobileserver.processes.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Stateless;

@Stateless
public class ControllerFacadeBean implements ControllerFacade {

	@EJB
	private ManageMobile mobileService;
	
	
	public List<MobileFunction> getFunctions() {
		return mobileService.getFunctions();
	}
	
	
	public int getMenuPageSize() {
		return mobileService.getMenuPageSize();
	}
	
}

server.app/los.mobile/srcServer/de/linogistix/mobileserver/processes/controller/ManageMobileBean.java
/*
 * Copyright (c) 2010-2013 LinogistiX GmbH
 * 
 * www.linogistix.com
 * 
 * Project: myWMS-LOS
*/
package de.linogistix.mobileserver.processes.controller;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

import javax.ejb.Stateless;

import de.linogistix.los.inventory.model.LOSPickingOrder;
import de.linogistix.mobileserver.processes.picking.PickingMobileComparator;
import de.linogistix.mobileserver.processes.picking.PickingMobilePos;


public class ManageMobileBean implements ManageMobile {
	
	
	public List<MobileFunction> getFunctions() {
		List<MobileFunction> functionList = new ArrayList<MobileFunction>();
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.info.InfoBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.goodsreceipt.GoodsReceiptBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.storage.StorageBackingBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.gr_direct.GRDirectBean", "MODE_GOODS_RECEIPT") );
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.gr_direct.GRDirectBean", "MODE_MATERIAL") );
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.picking.PickingMobileBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.shipping.ShippingBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.replenish.ReplenishMobileBean"));
		functionList.add(new MobileFunction("de.linogistix.mobile.processes.stocktaking.StockTakingBean"));
		
		return functionList;
	}
	

	public int getMenuPageSize() {
		return 3;
	}
	
	public Comparator<PickingMobilePos> getPickingComparator() {
		return new PickingMobileComparator(false);
	}
	
	public String getPickingSelectionText(LOSPickingOrder pickingOrder) {
		return pickingOrder.getNumber();
	}
}

server.app/los.mobile/WebContent/pages/processes/info/SelectType.jsp
<%-- 
  Copyright (c) 2010 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%--
The taglib directive below imports the JSTL library. If you uncomment it,
you must also add the JSTL library to the project. The Add Library... action
on Libraries node in Projects view can be used to add the JSTL 1.1 library.
--%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>


    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
        <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    
    <body class="verticalscroll" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" onload="load()">
        <f:view locale="#{InfoBean.locale}">
            <f:loadBundle var="bundle" basename ="de.linogistix.mobile.processes.info.InfoBundle" /> 
            
            <h:form id="Form" styleClass="form" >
                <%-- Page Title--%>
                <p id="pHeader"class="pageheader">
                	<h:outputText id="pagetitle" value="#{bundle.TitleSelectType}" styleClass="pagetitle"/>
	                <h:graphicImage id="logo" url="/pics/logo.gif" styleClass="logo"/>
               	</p>
                
                <div class="space">
                    <h:messages id="messages"  styleClass="error"/> 
                    
                    <table  width="100%" border="0" cellspacing="0">
                    	<colgroup>
							<col width="20%"/>
							<col width="80%"/>
						</colgroup>

	            		<tr><td>&#160;</td></tr>

                        <tr><td>
		                    <h:commandButton id="btUnitLoad" 
			                				 value="#{bundle.LabelUnitLoad}" 
			                				 action="#{InfoBean.processSelectUnitLoad}" 
			                				 styleClass="commandButton" 
			                				 rendered="#{InfoBean.unitLoadSelected}"  />
						</td></tr>
                        <tr><td>
		                    <h:commandButton id="btItemData" 
			                				 value="#{bundle.LabelItem}" 
			                				 action="#{InfoBean.processSelectItemData}" 
			                				 styleClass="commandButton" 
			                				 rendered="#{InfoBean.itemDataSelected}"  />
						</td></tr>
                        <tr><td>
		                    <h:commandButton id="btLocation" 
			                				 value="#{bundle.LabelLocation}" 
			                				 action="#{InfoBean.processSelectLocation}" 
			                				 styleClass="commandButton" 
			                				 rendered="#{InfoBean.locationSelected}"  />
						</td></tr>
                    </table>
                </div>
                

                <%-- Command Buttons --%>
                <div class="buttonbar">  
	                    <h:commandButton id="BUTTON_CANCEL" 
		                				 value="#{bundle.ButtonBack}" 
		                				 action="#{InfoBean.processSelectCancel}" 
		                				 styleClass="commandButton"  />
                </div>
            </h:form>
        </f:view> 
        <script type="text/javascript">
            
            function load() {            
                setFocus();    
            }    
            
            function setFocus() {
                document.getElementById('Form:btUnitLoad').focus();
            }    
            
        </script>
        
    </body>
</html>

server.app/los.mobile/WebContent/pages/processes/info/ShowUnitLoad.jsp
<%-- 
  Copyright (c) 2010 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%--
The taglib directive below imports the JSTL library. If you uncomment it,
you must also add the JSTL library to the project. The Add Library... action
on Libraries node in Projects view can be used to add the JSTL 1.1 library.
--%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
        <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    
    <body class="verticalscroll" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" onload="load()">
        <f:view locale="#{InfoBean.locale}">
            <f:loadBundle var="bundle" basename ="de.linogistix.mobile.processes.info.InfoBundle" /> 
            
            <h:form id="Form" styleClass="form" >
                <%-- Page Title--%>
                <p id="pHeader"class="pageheader">
                	<h:outputText id="pagetitle" value="#{bundle.TitleShowUnitLoad}" styleClass="pagetitle"/>
	                <h:graphicImage id="logo" url="/pics/logo.gif" styleClass="logo"/>
               	</p>
                
                <div class="space">
                    <h:messages id="messages"  styleClass="error"/> 
                    
                    <table  width="100%" border="0" cellspacing="0">
                    	<colgroup>
							<col width="20%"/>
							<col width="80%"/>
						</colgroup>
                    	
                    	<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="clientLabel" value="#{bundle.LabelClient}:" styleClass="param" rendered="#{InfoBean.showClient}"/> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="clientData" value="#{InfoBean.infoUnitLoad.clientNumber}" styleClass="label" rendered="#{InfoBean.showClient}"/>
                            </td>
                        </tr>
                        
                    	<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:commandLink id="locationLabel" value="#{bundle.LabelLocation}:" action="#{InfoBean.processUnitLoadLocation}" /> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="locationData" value="#{InfoBean.infoUnitLoad.locationName}" styleClass="label" />
                            </td>
                        </tr>
                        
                    	<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="unitLoadLabel" value="#{bundle.LabelUnitLoad}:" styleClass="param" /> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="unitLoadData" value="#{InfoBean.infoUnitLoad.label}" styleClass="label" />
                            </td>
                        </tr>

                    	<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="unitLoadTypeLabel" value="#{bundle.LabelType}:" styleClass="param" /> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="unitLoadTypeData" value="#{InfoBean.infoUnitLoad.type}" styleClass="label" />
                            </td>
                        </tr>

                        <tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:commandLink id="contentLabel" value="#{bundle.LabelContent}:" action="#{InfoBean.processUnitLoadStockUnit}" disabled="#{!InfoBean.unitLoadHasContent}"/>
                            </td> 
                            <td nowrap="nowrap">
                               	<h:outputLabel id="contentData" value="#{InfoBean.unitLoadContent}" styleClass="label" /> 
                            </td>
                        </tr>
                        
                    	<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:commandLink id="pickLabel" value="#{InfoBean.unitLoadOrderLabel}:" action="#{InfoBean.processUnitLoadOrder}" disabled="#{!InfoBean.unitLoadHasOrderContent}" />
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="pickData" value="#{InfoBean.unitLoadOrder}" styleClass="label"/>
                            </td>
                        </tr>
                        
                        
                  	</table>
                </div>
                

                <%-- Command Buttons --%>
                <div class="buttonbar">  
                    <h:commandButton id="BUTTON_CONTINUE" 
	                				 value="#{bundle.ButtonDone}" 
	                				 action="#{InfoBean.processStart}" 
	                				 styleClass="commandButton"  />
					&#160;
                    <h:commandButton id="BUTTON_BACK" 
									value="#{bundle.ButtonBack}" 
									onclick="goBack(); return false;" 
	                				styleClass="commandButton" 
	                				rendered="#{InfoBean.showUnitLoadBack}" />
                   	<h:commandButton id="BUTTON_PREV" 
	                				 value="<" 
	                				 action="#{InfoBean.processUnitLoadPrev}" 
	                				 styleClass="navigateButton"
	                				 rendered="#{InfoBean.unitLoadHasPrev || InfoBean.unitLoadHasNext}"
	                				 disabled="#{!InfoBean.unitLoadHasPrev}" /> 
                    <h:commandButton id="BUTTON_NEXT" 
	                				 value=">" 
	                				 action="#{InfoBean.processUnitLoadNext}" 
	                				 styleClass="navigateButton" 
	                				 rendered="#{InfoBean.unitLoadHasPrev || InfoBean.unitLoadHasNext}"
	                				 disabled="#{!InfoBean.unitLoadHasNext}" /> 
                </div>
            </h:form>
        </f:view> 
        <script type="text/javascript">
            
            function load() {            
                setFocus();    
            }    
            
            function setFocus() {
                document.getElementById('Form:BUTTON_CONTINUE').focus();
            }    

            function goBack() {
                window.history.back();
                window.location.href = window.location.pathname + window.location.search;
            }
            
        </script>
        
    </body>
</html>