server.app/los.mobile/src/de/linogistix/mobile/processes/picking/PickingMobileBean.java
/*
 * Copyright (c) 2011-2013 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.processes.picking;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

import javax.faces.event.ValueChangeEvent;
import javax.faces.model.SelectItem;

import org.apache.log4j.Logger;
import org.mywms.facade.FacadeException;
import org.mywms.model.Client;

import de.linogistix.los.model.State;
import de.linogistix.mobile.common.gui.bean.BasicDialogBean;
import de.linogistix.mobile.common.system.JSFHelper;
import de.linogistix.mobileserver.processes.picking.PickingMobileOrder;
import de.linogistix.mobileserver.processes.picking.PickingMobilePos;

/**
 * @author krane
 *
 */
public class PickingMobileBean extends BasicDialogBean {
	Logger log = Logger.getLogger(PickingMobileBean.class);


	// ***********************************************************************
	// Switches. Configured with system properties
	// ***********************************************************************
	
	protected Long selectedOrderId;
	protected List<SelectItem> orderSelectList;
	
	protected PickingMobileData data;
	protected List<String> serialList = null;
	
	protected String inputCode = "";
	protected String inputPrinter = "";
	protected BigDecimal amountTaken;
	protected BigDecimal amountRemaining;
	protected boolean locationCounted = false;
	protected String currentPrinter = null;
	protected Long currentId = null;

	protected boolean showClient = true;

	
	public PickingMobileBean() {
		super();
		
		data = new PickingMobileData();
		
		Client client = data.getDefaultClient();
		showClient = (client == null);
	}

	@Override
	public String getNavigationKey() {
		return getNavigationKey(PickingMobileNavigation.PICK_START);
	}

	@Override
	public String getTitle() {
		return resolve("TitlePickSingle");
	}

	String selClient;
	String selCustomerOrderNumber;
	String selCustomerOrderExternalNumber;
	String selNumPos;
	String selDate;
	String selStrategy;
	
	public void init() {
		log.debug("init");
		amountTaken = null;
		amountRemaining = null;
		locationCounted = false;
		inputCode = "";
		currentPrinter = null;
		orderSelectList = null;
		currentId = null;

		selClient = "";
		selCustomerOrderNumber = "";
		selCustomerOrderExternalNumber = "";
		selNumPos = "";
		selDate = "";
		selStrategy  ="";
		
		data.reset();
	}
	
	@Override
	public void init(String[] args) {
		super.init(args);
		init();
	}

	
	protected void initPos() {
		log.debug("Initialize position");
		inputCode = null;
		amountTaken = null;
		amountRemaining = null;
		locationCounted = false;
		currentId = null;
	}

	// ***********************************************************************
	// StartPicking.jsp
	// ***********************************************************************
	public String processStartPicking() {
    	log.debug("processStartPicking");
		init();
		try {
			data.resume(true);
		} catch (FacadeException e) {
			JSFHelper.getInstance().message( e.getLocalizedMessage() );
			return "";
		}

		if( data.getNumOrders()>0 ) {
			JSFHelper.getInstance().message( resolve("MsgRestore") );
			return getNavigationKey(PickingMobileNavigation.PICK_ORDER_SUMMARY);
		}
		return getNavigationKey(PickingMobileNavigation.PICK_ORDER_SELECT);
	}
	
	
	
	// ***********************************************************************
	// OrderSelect.jsp
	// ***********************************************************************
	protected List<SelectItem> getCalculatedPickingOrders(String code) {
		return data.getCalculatedPickingOrders( code, true, true );
	}
	public String processOrderSelect(){
		String code = inputCode == null ? "" : inputCode.trim();
		inputCode = "";
		
		if( code.length() > 0 ) {
			orderSelectList = getCalculatedPickingOrders( code );
			if( orderSelectList == null || orderSelectList .size() == 0 ) {
				orderSelectList = new ArrayList<SelectItem>();
				JSFHelper.getInstance().message( resolve("MsgNothingFound") );
				selectedOrderId=null;
				loadSelectedOrder();
				return "";
			}
			try{
				selectedOrderId = (Long)orderSelectList.get(0).getValue();
			} catch( Throwable t ) {
		    	log.error("Exception: "+t.getClass().getSimpleName()+", "+t.getMessage(), t);
			}
			if( orderSelectList.size() > 1 ) {
				loadSelectedOrder();
				return "";
			}
			orderSelectList = null;
		}

		if( selectedOrderId == null ) {
			JSFHelper.getInstance().message( resolve("MsgSelectEmpty") );
			orderSelectList = null;
			return "";
		}
		
		try {
			data.loadOrder(selectedOrderId);
			orderSelectList = null;
			if( isShowOrderInfo() ) {
				return getNavigationKey(PickingMobileNavigation.PICK_ORDER_INFO);
			}
			else {
				data.startPicking();
				if( !data.setFirstPick() ) {
					JSFHelper.getInstance().message( resolve("MsgNoPos") );
					return "";
				}
				return getNavigationKey(PickingMobileNavigation.PICK_PICKFROM);
			}
		} catch (FacadeException e) {
			orderSelectList = null;
			JSFHelper.getInstance().message( e.getLocalizedMessage(getUIViewRoot().getLocale()) );
			return "";
		}

		
	}
	
	public String processOrderSelectCancel() {
		try {
			data.removeAllOrders();
		} catch (FacadeException e) {
			JSFHelper.getInstance().message( e.getLocalizedMessage(getUIViewRoot().getLocale()) );
			return "";
		}
			
		init();
		return getNavigationKey(PickingMobileNavigation.PICK_MENU);
	}

	public List<SelectItem> getOrderList(){
		String logStr = "getOrderList ";

		if( orderSelectList == null ) {
			selectedOrderId = null;

			orderSelectList = getCalculatedPickingOrders( null );
			if( orderSelectList == null ) {
				orderSelectList = new ArrayList<SelectItem>();
			}
			if( orderSelectList.size() > 0 ) {
				try{
					selectedOrderId = (Long)orderSelectList.get(0).getValue();
				} catch( Throwable t ) {
			    	log.error("Exception: "+t.getClass().getSimpleName()+", "+t.getMessage(), t);
				}
			}
			loadSelectedOrder();
		}
		
		log.info(logStr+"Found "+orderSelectList.size()+" orders");
		return orderSelectList;
	}

	public void setSelectedOrder(String sel){
		selectedOrderId = null;
		try{
			selectedOrderId = Long.valueOf(sel);
		} catch( Throwable t ) {}
	}
	
	public String getSelectedOrder(){
		if( selectedOrderId == null ) {
			return null;
		}
		
		return selectedOrderId.toString();
	}
	
    public void orderSelectionChanged(ValueChangeEvent vce) {
    	String sel = (String)vce.getNewValue();
    	setSelectedOrder(sel);
    	loadSelectedOrder();
    }

    protected void loadSelectedOrder() {
    	if( selectedOrderId != null ) {
	    	PickingMobileOrder order = data.readOrder(selectedOrderId);
	    	selClient = order.clientNumber;
	    	selCustomerOrderNumber = order.customerOrderNumber;
	    	selCustomerOrderExternalNumber = order.customerOrderExternalNumber;
	    	selNumPos = String.valueOf(order.numPos);
	    	selDate = order.created;
	    	selStrategy = order.strategy;
    	}
    	else {
	    	selClient = "";
	    	selCustomerOrderNumber = "";
	    	selCustomerOrderExternalNumber = "";
	    	selNumPos = "";
	    	selDate = "";
	    	selStrategy = "";
    	}
    }
    
	// ***********************************************************************
	// PickToPrint.jsp
	// ***********************************************************************
	public String processPickToPrintSelect(){
		String logStr = "processPickToPrintSelect ";
		String code = inputPrinter == null ? "" : inputPrinter.trim();
		inputPrinter = "";

		log.debug(logStr+getTrace()+", input="+code);
		
		currentPrinter = (code.length()==0 ? null : code);

		try {
			data.printLabel( currentPrinter );
		} catch (FacadeException e) {
			JSFHelper.getInstance().message( e.getLocalizedMessage(getUIViewRoot().getLocale()) );
			return "";
		}

		return getNavigationKey(PickingMobileNavigation.PICK_PICKTO_TARGET);
	}
	
	public String processPickToPrintSkip(){
		String logStr = " processPickToPrintSkip";
		log.debug(logStr+getTrace());

		inputPrinter = "";
		currentPrinter = null;
		return getNavigationKey(PickingMobileNavigation.PICK_PICKTO_TARGET);
	}

	// ***********************************************************************
	// OrderSummary.jsp
	// ***********************************************************************
	public String processOrderSummary(){
		return processOrderInfo();
	}
	
	public String processOrderSummaryCancel(){
		return processOrderInfoCancel();
	}
	
	// ***********************************************************************
	// OrderInfo.jsp
	// ***********************************************************************
	public String processOrderInfo(){
		String logStr="processOrderInfo ";
		log.debug(logStr+getTrace());
		
		try {
			data.startPicking();
			
			if( data.setFirstPick() ) {
				return getNavigationKey(PickingMobileNavigation.PICK_PICKFROM);
			}
		} catch (FacadeException e) {
			JSFHelper.getInstance().message( e.getLocalizedMessage(getUIViewRoot().getLocale()) );
			return "";
		}
		
		log.error(logStr+"No pick found to process");
		JSFHelper.getInstance().message( resolve("MsgNoPos") );
		return processOrderInfoCancel();
	}
	
	public String processOrderInfoCancel(){
		String logStr = "processOrderInfoCancel ";
		log.debug(logStr+getTrace());

		inputCode = "";

		try {
			data.startPutAway();
			if( data.getCurrentPickTo() != null ) {
				return getNavigationKey(PickingMobileNavigation.PICK_PICKTO_TARGET);
			}
			data.removeAllOrders();
		} catch (FacadeException e) {
			JSFHelper.getInstance().message( e.getLocalizedMessage(getUIViewRoot().getLocale()) );
			return "";
		}
		
		init();
		
		return getNavigationKey(PickingMobileNavigation.PICK_ORDER_SELECT);
	}
	
	// ***********************************************************************
	// PickFrom.jsp
	// ***********************************************************************
	public String processPickFrom(){
		String logStr = "processPickFrom ";

server.app/los.mobile/src/de/linogistix/mobile/processes/shipping/ShippingBean.java
/*
 * Copyright (c) 2006 - 2013 LinogistiX GmbH
 * 
 * www.linogistix.com
 * 
 * Project: myWMS-LOS
*/
package de.linogistix.mobile.processes.shipping;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

import javax.faces.event.ValueChangeEvent;
import javax.faces.model.SelectItem;

import org.apache.log4j.Logger;
import org.mywms.facade.FacadeException;

import de.linogistix.los.inventory.facade.LOSGoodsOutFacade;
import de.linogistix.los.inventory.facade.LOSGoodsOutTO;
import de.linogistix.los.inventory.query.dto.LOSGoodsOutRequestTO;
import de.linogistix.los.util.StringTools;
import de.linogistix.mobile.common.gui.bean.BasicDialogBean;
import de.linogistix.mobile.common.system.JSFHelper;

/**
 *
 * @author krane
 */
public class ShippingBean extends BasicDialogBean {
	private static final Logger log = Logger.getLogger(ShippingBean.class);

	protected LOSGoodsOutFacade goFacade;
	protected LOSGoodsOutTO currentOrderTO = null;
	protected String inputUnitLoadLabel = "";
	protected List<SelectItem> orderList = null; 
	
	public ShippingBean() {
		super();
		goFacade = super.getStateless(LOSGoodsOutFacade.class);
	}
	
	public String getNavigationKey() {
		return ShippingNavigation.SHIPPING_SELECT_ORDER.name();
	}
	
	public String getTitle() {
		return resolve("Shipping");
	}

	/** 
	 * reset all variables to default values
	 */
	protected void init() {
		inputUnitLoadLabel = "";
		currentOrderTO = null;
		orderList = null;
	}
	
	

	public String processSelectOrder() {
		orderList = null;
		if( currentOrderTO == null ) {
			JSFHelper.getInstance().message(resolve("MsgOrderNotFound"));
			return "";
		}
		
		try {
			goFacade.start(currentOrderTO.getOrderId());
		} 
		catch (FacadeException e) {
			JSFHelper.getInstance().message(e.getLocalizedMessage(getLocale()));
			return "";
		}
		
		return ShippingNavigation.SHIPPING_SCAN_UNITLOAD.toString();
	}
	

	public String processCancelSelectOrder() {
		init();
		return ShippingNavigation.SHIPPING_BACK_TO_MENU.toString();
	}

	
	public String processShowInfo() {
		return ShippingNavigation.SHIPPING_SHOW_INFO.toString();
	}


	public String processEnterUnitLoad() {
		if( currentOrderTO == null ) {
			JSFHelper.getInstance().message(resolve("MsgOrderNotLoaded"));
			return ShippingNavigation.SHIPPING_SELECT_ORDER.toString();
		}
		
		if( inputUnitLoadLabel == null ) {
			JSFHelper.getInstance().message(resolve("MsgEnterUnitLoad"));
			return ShippingNavigation.SHIPPING_SCAN_UNITLOAD.toString();
		}
		inputUnitLoadLabel = inputUnitLoadLabel.trim();
		if( inputUnitLoadLabel.length() == 0 ) {
			JSFHelper.getInstance().message(resolve("MsgEnterUnitLoad"));
			return ShippingNavigation.SHIPPING_SCAN_UNITLOAD.toString();
		}
		
		try {
			goFacade.finishPosition(inputUnitLoadLabel, currentOrderTO.getOrderId());
		} catch (FacadeException e) {
			JSFHelper.getInstance().message(e.getLocalizedMessage(getLocale()));
			return "";
		}
		
		inputUnitLoadLabel = "";
		
		try {
			currentOrderTO = goFacade.getOrderInfo(currentOrderTO.getOrderId());
			if( currentOrderTO.isFinished() ) {
				goFacade.finish(currentOrderTO.getOrderId());
				return ShippingNavigation.SHIPPING_SHOW_SUMMARY.toString();
			}
		} catch (FacadeException e) {
			JSFHelper.getInstance().message(e.getLocalizedMessage(getLocale()));
			return "";
		}
		
		return ShippingNavigation.SHIPPING_SCAN_UNITLOAD.toString();
	}
	
	public String processCancelUnitLoad() {
		if( currentOrderTO == null ) {
			JSFHelper.getInstance().message(resolve("MsgOrderNotLoaded"));
			return ShippingNavigation.SHIPPING_SELECT_ORDER.toString();
		}
		
		try {
			goFacade.cancel(currentOrderTO.getOrderId());
			return ShippingNavigation.SHIPPING_SHOW_SUMMARY.toString();
		} catch (FacadeException e) {
			JSFHelper.getInstance().message(e.getLocalizedMessage(getLocale()));
			return ShippingNavigation.SHIPPING_SELECT_ORDER.toString();
		}

	}
	
	public String processShowUnitLoad() {
		return ShippingNavigation.SHIPPING_SCAN_UNITLOAD.toString();
	}
	
	
    public List<SelectItem> getOrderList() {
    	
		if( orderList == null ) {
			orderList = new ArrayList<SelectItem>();

			List<LOSGoodsOutRequestTO> outRequestList = goFacade.getRaw();
			if (outRequestList != null && (outRequestList.isEmpty() == false)) {
				for (LOSGoodsOutRequestTO order : outRequestList) {
					String displayname = order.getNumber();
					String customerOrderNumber = order.getCustomerOrderNumber();
					if( !StringTools.isEmpty(customerOrderNumber) ) {
						displayname += " ("+customerOrderNumber+")";
					}
					orderList.add(new SelectItem(order.getNumber(), displayname));
				}
			}
		}

    	
		return orderList;
    }


    public void selectedOrderChanged(ValueChangeEvent vce) {
		currentOrderTO = null;
    	try {
        	String orderNumber = null;
    		orderNumber = (String)vce.getNewValue();
    		log.info("Selected order: " + orderNumber);
    		currentOrderTO = goFacade.load(orderNumber);
    	}
    	catch( Exception e) {
    		log.error(e.getMessage(), e);
    	}
    }
    
	public String processSummaryFinish() {
		init();
		return ShippingNavigation.SHIPPING_SELECT_ORDER.toString();
	}
	
	public String processInfoFinish() {
		return ShippingNavigation.SHIPPING_SCAN_UNITLOAD.toString();
	}
	
	public String getOrderNumber() {
		return currentOrderTO == null ? "" : currentOrderTO.getOrderNumber();
	}
	
	public void setOrderNumber(String orderNumber) {
	}
	
	public String getComment() {
		return currentOrderTO == null ? "" : currentOrderTO.getComment();
	}

	public String getNextUnitLoadLabel() {
		return currentOrderTO == null ? "" : currentOrderTO.getNextUnitLoadLabelId();
	}
	
	public String getNextLocation() {
		return currentOrderTO == null ? "" : currentOrderTO.getNextLocationName();
	}
	
	public String getNumPosDone() {
		return currentOrderTO == null ? "" : Long.valueOf(currentOrderTO.getNumPosDone()).toString();
	}

	public String getNumPosOpen() {
		return currentOrderTO == null ? "" : Long.valueOf(currentOrderTO.getNumPosOpen()).toString();
	}
	
	public String getNumPos() {
		if( currentOrderTO == null ) {
			return "";
		}
		long numPos = currentOrderTO.getNumPosDone() + currentOrderTO.getNumPosOpen(); 
		return Long.valueOf(numPos).toString();
	}

	public String getInputUnitLoadLabel() {
		return inputUnitLoadLabel;
	}

	public void setInputUnitLoadLabel(String inputUnitLoadLabel) {
		this.inputUnitLoadLabel = inputUnitLoadLabel;
	}


	protected ResourceBundle getResourceBundle() {
		ResourceBundle bundle;
		Locale loc;
		loc = getUIViewRoot().getLocale();
		bundle = ResourceBundle.getBundle("de.linogistix.mobile.processes.shipping.ShippingBundle", loc);
		return bundle;
	}

}


server.app/los.mobile/srcServer/de/linogistix/mobileserver/processes/controller/ControllerFacadeBean.java
/*
 * Copyright (c) 2010 LinogistiX GmbH
 * 
 * www.linogistix.com
 * 
 * Project: myWMS-LOS
*/
package de.linogistix.mobileserver.processes.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Stateless;

@Stateless
public class ControllerFacadeBean implements ControllerFacade {

	@EJB
	private ManageMobile mobileService;
	
	
	public List<MobileFunction> getFunctions() {
		return mobileService.getFunctions();
	}
	
	
	public int getMenuPageSize() {
		return mobileService.getMenuPageSize();
	}
	
}

server.app/los.mobile/WebContent/pages/processes/shipping/ScanUnitLoad.jsp
<%-- 
  Copyright (c) 2006 - 2010 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%--
The taglib directive below imports the JSTL library. If you uncomment it,
you must also add the JSTL library to the project. The Add Library... action
on Libraries node in Projects view can be used to add the JSTL 1.1 library.
--%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
        <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    
    <body class="verticalscroll" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" onload="load()">
        <f:view locale="#{ShippingBean.locale}">
            <f:loadBundle var="bundle" basename ="de.linogistix.mobile.processes.shipping.ShippingBundle" /> 
            
            <h:form id="Form" styleClass="form" >
                <%-- Page Title--%>
                <p class="pageheader">
                	<h:outputText id="pagetitle" value="#{bundle.TitleUnitload} (#{ShippingBean.numPosDone + 1}/#{ShippingBean.numPos})" styleClass="pagetitle"/>
	                <h:graphicImage id="logo" url="/pics/logo.gif" styleClass="logo"/>
               	</p>


                <div class="space">
                    <h:messages id="messages" styleClass="error"/>
                     
                    <table  width="100%" border="0" cellspacing="0">
                    	<colgroup>
							<col width="20%"/>
							<col width="80%"/>
						</colgroup>
						
						<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="orderLabel" value="#{bundle.LabelOrder}:" styleClass="param" /> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="orderData" value="#{ShippingBean.orderNumber}" styleClass="value" />
                            </td>
                        </tr>
                    </table>
                    <table  width="100%" border="0" cellspacing="0">
                    	<colgroup>
							<col width="20%"/>
							<col width="80%"/>
						</colgroup>
						
						<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="locLabel" value="#{bundle.LabelNextLocation}:" styleClass="param" /> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="locData" value="#{ShippingBean.nextLocation}" styleClass="value" />
                            </td>
                        </tr>
						<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="ulLabel" value="#{bundle.LabelNextUnitLoad}:" styleClass="param" /> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="ulData" value="#{ShippingBean.nextUnitLoadLabel}" styleClass="value" />
                            </td>
                        </tr>
                        <tr><td>&#160;</td></tr>
                        <tr>
                            <td colspan="2">
                            	<h:outputLabel id="input1Label" value="#{bundle.LabelEnterUnitLoad}" styleClass="label" />
                            </td>
                        </tr>
						<tr>
                            <td colspan="2">
                               	<h:inputText id="input1" 
                             			 value="#{ShippingBean.inputUnitLoadLabel}" 
                             			 styleClass="input" /> 
                            </td>
                        </tr>

                    </table>
                </div>
                
				<h:inputText value="IE-Dummy" style="display:none" />

                <%-- Command Buttons --%>
                <div class="buttonbar">  
	                    <h:commandButton id="BUTTON_CONTINUE" 
		                				 value="#{bundle.LabelContinue}" 
		                				 action="#{ShippingBean.processEnterUnitLoad}" 
		                				 styleClass="commandButton"  />
	                    <h:commandButton id="BUTTON_INFO" 
		                				 value="#{bundle.LabelInfo}" 
		                				 action="#{ShippingBean.processShowInfo}" 
		                				 styleClass="commandButton"  />
	                    <h:commandButton id="BUTTON_CANCEL" 
		                				 value="#{bundle.LabelCancel}" 
		                				 action="#{ShippingBean.processCancelUnitLoad}" 
		                				 styleClass="commandButton"  />
                </div>
                
            </h:form>
        </f:view> 
        
        <script type="text/javascript">
            
            <%--            function setRow() {
                document.getElementById("view<%=renderResponse.get Namespace()%>:dt1").rows[1].style.backgroundColor="red";            
            }    --%>
                
                function load() {            
                    setFocus();    
                }    
                
                function setFocus() {
                    document.getElementById('Form:input1').focus();
                }    
                
        </script>
        
    </body>
</html>

server.app/los.mobile/WebContent/pages/processes/shipping/ShowInfo.jsp
<%-- 
  Copyright (c) 2006 - 2010 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%--
The taglib directive below imports the JSTL library. If you uncomment it,
you must also add the JSTL library to the project. The Add Library... action
on Libraries node in Projects view can be used to add the JSTL 1.1 library.
--%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
        <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    
    <body class="verticalscroll" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" onload="load()">
        <f:view locale="#{ShippingBean.locale}">
            <f:loadBundle var="bundle" basename ="de.linogistix.mobile.processes.shipping.ShippingBundle" /> 
            
            <h:form id="Form" styleClass="form" >
                <%-- Page Title--%>
                <p class="pageheader">
                	<h:outputText id="pagetitle" value="#{bundle.TitleInfo}" styleClass="pagetitle"/>
	                <h:graphicImage id="logo" url="/pics/logo.gif" styleClass="logo"/>
                </p>

                <div class="space">
                    <h:messages id="messages" styleClass="error"/>
                     
                    <table  width="100%" border="0" cellspacing="0">
                    	<colgroup>
							<col width="20%"/>
							<col width="80%"/>
						</colgroup>
						
						<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="orderLabel" value="#{bundle.LabelOrder}:" styleClass="param" /> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="orderData" value="#{ShippingBean.orderNumber}" styleClass="value" />
                            </td>
                        </tr>
                    </table>
                    
                    <table  width="100%" border="0" cellspacing="0">
                    	<colgroup>
							<col width="20%"/>
							<col width="80%"/>
						</colgroup>
						
						<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="ul2Label" value="#{bundle.LabelNumPosOpen}:" styleClass="param" rendered="#{ShippingBean.numPosOpen != ''}"/> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="ul2Data" value="#{ShippingBean.numPosOpen}" styleClass="value" />
                            </td>
                        </tr>
						<tr>
                            <td nowrap="nowrap" style="padding-right:20px">
                            	<h:outputLabel id="ul1Label" value="#{bundle.LabelNumPosDone}:" styleClass="param" /> 
                            </td>
                            <td nowrap="nowrap">
                              	<h:outputLabel id="ul1Data" value="#{ShippingBean.numPosDone}" styleClass="value" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h:outputText value="#{bundle.LabelComment}:" styleClass="param"/>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" style="padding-left:20px; font-size:smaller;">
                               	<h:outputLabel id="comment" value="#{ShippingBean.comment}" styleClass="value" />
                            </td>

                        </tr>
                       
                    </table>
                </div>
                
                
                <%-- Command Buttons --%>
                <div class="buttonbar">  
	                    <h:commandButton id="BUTTON_CONTINUE" 
		                				 value="#{bundle.LabelBack}" 
		                				 action="#{ShippingBean.processShowUnitLoad}" 
		                				 styleClass="commandButton"  />
                </div>
            </h:form>
        </f:view> 
        <script type="text/javascript">
            
            function load() {            
                setFocus();    
            }    
            
            function setFocus() {
                document.getElementById('Form:BUTTON_CONTINUE').focus();
            }    
            
        </script>
    </body>
</html>