server.app/los.mobile/src/de/linogistix/mobile/common/gui/bean/BasicDialogBean.java
package de.linogistix.mobile.common.gui.bean;

public abstract class BasicDialogBean extends BasicBackingBean {

	/**
	 * @return The key of the faces-config.xml file
	 */
	public abstract String getNavigationKey();
	
	/**
	 * @return The title of the dialog.
	 */
	public abstract String getTitle();

	/**
	 * Initialization of the dialog. 
	 * Overwrite this method to use the arguments given by the MenuBean 
	 */
	public void init( String[] args ){
	}
}

server.app/los.mobile/src/de/linogistix/mobile/common/gui/bean/NotifyDescriptorExt.java
/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.common.gui.bean;

import java.util.List;

import de.linogistix.mobile.common.listener.ButtonListener;
import de.linogistix.mobile.common.object.Constants;
import de.linogistix.mobile.common.system.JSFHelper;


/**
 *
 * @author artur
 */
public class NotifyDescriptorExt extends BasicBackingBean {

    NotifyDescriptorExtBean bean;
    final static String NOTIFY_DESCRIPTOR_EXT_PANEL = "NotifyDescriptorExtPanel";
    final static String NOTIFY_DESCRIPTOR_EXT_BEAN = "NotifyDescriptorExtBean";
    NotifyEnum notifyType;
    
    public NotifyDescriptorExt(String icon, String pageTitle, String message, List<String> buttonTextList) {
    	notifyType = NotifyEnum.INFORMATION;
    	setBean(icon, pageTitle, message, buttonTextList);
    }
    
    public NotifyDescriptorExt(final NotifyEnum notify, String message, List<String> buttonTextList) {
        this.notifyType = notify;
    	switch (notify) {
            case WARNING:
                setBean(Constants.WARNING_ICON, resolve("Warning", new Object[]{}), message, buttonTextList);
                break;
            case ERROR:
                setBean(Constants.ERROR_ICON, resolve("Error", new Object[]{}), message, buttonTextList);
                break;
            case INFORMATION:
                setBean(Constants.INFORMATION_ICON, resolve("Information", new Object[]{}), message, buttonTextList);
                break;
            case QUESTION:
                setBean(Constants.QUESTION_ICON, resolve("Question", new Object[]{}), message, buttonTextList);
                break;
            case INPUT:
            	setBean(Constants.QUESTION_ICON, resolve("Question", new Object[]{}), message, buttonTextList);
                break;
            case HELP:
                setBean(Constants.HELP_ICON, resolve("Help", new Object[]{}), message, buttonTextList);
                break;
        }
    }

    public NotifyDescriptorExt(NotifyEnum input, String pageTitle,
			List<String> buttonTextList, String paramDefault) {
		this(input, pageTitle, buttonTextList);
		bean.setParam(paramDefault);
	}

	private void setBean(String icon, String pageTitle, String message, List<String> buttonTextList) {
        bean = (NotifyDescriptorExtBean) JSFHelper.getInstance().getSessionBean(NotifyDescriptorExtBean.class);
        if (bean == null) {
            bean = new NotifyDescriptorExtBean();
            JSFHelper.getInstance().setSessionBean(bean);
        }
        bean.setIcon(icon);
        bean.setPageTitle(pageTitle);
        bean.setTitle(pageTitle);
        bean.setMessage(message);
        bean.setButtons(buttonTextList);
        if (this.notifyType == NotifyEnum.INPUT){
        	bean.setParam(new String());
        }
    }

    public String setCallbackListener(ButtonListener listener) {
        bean.setCallbackListener(listener);
        return NOTIFY_DESCRIPTOR_EXT_PANEL;
    }

    public String getParam(){
    	return bean.getParam();
    }
    
    public enum NotifyEnum {

        WARNING,
        INFORMATION,
        QUESTION,
        INPUT,
        ERROR,
        HELP
    }
}

server.app/los.mobile/src/de/linogistix/mobile/common/gui/bean/NotifyDescriptorExtBean.java
/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.common.gui.bean;

import java.io.Serializable;
import java.util.List;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;

import de.linogistix.mobile.common.listener.ButtonListener;


/**
 *
 * @author artur
 */
public class NotifyDescriptorExtBean extends BasicBackingBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private String pageTitle;
    private String title;
    private String icon;
    private String message;
    
    private String param;
    
    private boolean visibleParam;

    List<String> buttonList;
    ButtonListener listener;

    public NotifyDescriptorExtBean() {

    }

    public void setButtons(List<String> buttonList) {
        this.buttonList = buttonList;
    }
    
    public void setParam(String param){
    	this.param = param;
    	this.visibleParam = true;
    	
    }

    private String getButtonText(int buttonNumber) {
        if (buttonList != null) {
            if (buttonList.size() >= buttonNumber) {
                return buttonList.get(buttonNumber - 1);
            }
        }
        return "";
    }

    public void setCallbackListener(ButtonListener listener) {
        this.listener = listener;
    }

    public String getButton1Text() {
        return getButtonText(1);
    }

    public String getButton2Text() {
        return getButtonText(2);

    }

    public String getButton3Text() {
        return getButtonText(3);

    }

    public String getButton4Text() {
        return getButtonText(4);

    }

    public String getButton5Text() {
        return getButtonText(5);
    }

    public String button1ActionPerformedListener() {
        return listener.buttonClicked(1, this);
    }

    public String button2ActionPerformedListener() {
        return listener.buttonClicked(2, this);
    }

    public String button3ActionPerformedListener() {
        return listener.buttonClicked(3, this);
    }

    public String button4ActionPerformedListener() {
        return listener.buttonClicked(4, this);
    }

    public String button5ActionPerformedListener() {
        return listener.buttonClicked(5, this);
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getPageTitle() {
        return pageTitle;
    }

    public void setPageTitle(String pageTitle) {
        this.pageTitle = pageTitle;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    private boolean isVisible(int buttonNumber) {
        if (buttonList != null) {
            if (buttonList.size() >= buttonNumber) {
                return true;
            }
        }
        return false;

    }

    public boolean isVisible1() {
        return isVisible(1);
    }

    public boolean isVisible2() {
        return isVisible(2);
    }

    public boolean isVisible3() {
        return isVisible(3);
    }

    public boolean isVisible4() {
        return isVisible(4);
    }

    public boolean isVisible5() {
        return isVisible(5);
    }

	public String getParam() {
		return param;
	}

	public boolean isVisibleParam() {
		return visibleParam;
	}
	
	 public void paramValidator(FacesContext context, UIComponent toValidate, Object value) {
	 
	 }
}

server.app/los.mobile/src/de/linogistix/mobile/processes/login/gui/bean/CenterBean.java
/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.processes.login.gui.bean;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.event.ActionListener;
import javax.faces.validator.ValidatorException;
import javax.servlet.http.HttpServletRequest;

import de.linogistix.mobile.common.gui.bean.BasicBackingBean;
import de.linogistix.mobile.common.system.JSFHelper;
import de.linogistix.mobile.processes.login.NavigationEnum;

/**
 * 
 * @author artur
 */
public class CenterBean extends BasicBackingBean implements ActionListener {
	String login;
	String password = "";
	String test;

	public String test() {
		System.out.println("test");
		return "";
	}

	public String getTest() {
		System.out.println("getTest");
		return "j_security_check";
	}

	public void setTest(String test) {
		System.out.println("setTest");
		this.test = test;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String loginActionPerformedListener() {
		/*
		 * ServletRequest request = (ServletRequest)
		 * FacesContext.getCurrentInstance().getExternalContext().getRequest();
		 * String s = (String)request.getAttribute("test");
		 * System.out.println("test = "+s);
		 */
		JSFHelper.getInstance().printRequest();
		JSFHelper.getInstance().printRequestMap();

		return NavigationEnum.controller_CenterPanel.toString();
	}

	public void validatePassword(FacesContext context, UIComponent component,
			Object value) throws ValidatorException {

	}

	public void beforePhase(javax.faces.event.PhaseEvent e) {
		HttpServletRequest req = (HttpServletRequest) e.getFacesContext()
				.getExternalContext().getRequest();
		req.getSession(true);

	}

	public void processAction(ActionEvent e) {

	}

}

server.app/los.mobile/src/de/linogistix/mobile/common/gui/jsp/JSPLoginBean.java
/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.common.gui.jsp;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import de.linogistix.mobile.common.gui.bean.BasicBackingBean;
import de.linogistix.mobile.common.system.JSFHelper;


/**
 *
 * @author artur
 */
public class JSPLoginBean extends BasicBackingBean {

    private String logout = resolve("Login", new Object[]{});


	private String sessionExpiredValidator;
    private String message;


    public String getLogin() {
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        context.getRequest();
        return logout;
    }

    public void setLogin(String login) {
        this.logout = login;
    }

    public String getSessionExpiredValidator() {
        JSFHelper.getInstance();
        return "";
    }

    public void setSessionExpiredValidator(String sessionExpiredValidator) {
        this.sessionExpiredValidator = sessionExpiredValidator;
    }

    public String getMessage() {
        JSFHelper helper = JSFHelper.getInstance();

        if (helper.getRequestQueryString() != null) {
            if (helper.getRequestQueryString().equals("errors=true")) {
                return getHTMLMessage(resolve("UserOrPasswordWrong"));
            }
            if (helper.getRequestQueryString().equals("errors=timeout")) {            
                return getHTMLMessage(resolve("SessionTimeoutMessage"));
            }
        }
        return "";
    }

    private String getHTMLMessage(String message) {
        return "<ul id='messages' class='error'><li>" + message + "</li></ul>";
    }

    public void setMessage(String message) {
        this.message = message;
    }

    
    
}

server.app/los.mobile/src/de/linogistix/mobile/common/gui/jsp/JSPLogoutBean.java
/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.mobile.common.gui.jsp;

import de.linogistix.mobile.common.gui.bean.BasicBackingBean;

/**
 *
 * @author artur
 */
public class JSPLogoutBean extends BasicBackingBean {

    private String login = resolve("Login");
   
    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }
}

server.app/los.mobile/WebContent/pages/common/gui/component/NotifyDescriptorExtPanel.jsp
<%-- 
  Copyright (c) 2006 - 2010 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%--
The taglib directive below imports the JSTL library. If you uncomment it,
you must also add the JSTL library to the project. The Add Library... action
on Libraries node in Projects view can be used to add the JSTL 1.1 library.
--%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
        <%--    <link rel="stylesheet" type="text/css" href="pages/picking/stylesheet.css" />--%>
        <%--  <link rel="stylesheet" type="text/css" href="stylesheet.css" /> --%>
        <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    
    <f:loadBundle var="bundle" basename ="de.linogistix.mobile.res.Bundle" />
    
    <body class="verticalscroll" topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" onload="load()">
        <f:view>
            <f:loadBundle var="bundle" basename ="de.linogistix.mobile.res.Bundle" /> 
            
            <h:form id="successForm" styleClass="form">
                <%-- Page Title--%>
                <p id="pHeader"class="pageheader">
	                <h:outputText id="pagetitle" value="#{NotifyDescriptorExtBean.pageTitle}" styleClass="pagetitle"/>
	                <h:graphicImage id="logo" url="/pics/logo.gif" styleClass="logo"/>
                </p>
                <%-- Form --%>
                <p></p>
                <%-- User (Driver) --%>   
                <div class="space">
                    <%--                <h:outputFormat id="infoMsg"  value="" styleClass="info"/> --%>
                    
                    <table  width="100%" border="0" cellspacing="0">
                        <tr>
                            <td width="0" > <h:graphicImage id="infoImg" url="#{NotifyDescriptorExtBean.icon}" /></td>                                                                                                               
                            <th scope="col">&nbsp;</th>
                            <td width="100%"><h:outputText id="message" value="#{NotifyDescriptorExtBean.message}" escape="false" styleClass="label"/></td>
                        </tr>
                        <tr>
                        	<td width="0" > <h:outputText id="paramTextFieldLabel" value="" escape="false" styleClass="label"/></td>                   
                            <th scope="col">&nbsp;</th>
                            <td width="100%">
                            	<h:inputText id="paramTextField" 
                            		validator="#{NotifyDescriptorExtBean.paramValidator}" 
                            		value="#{NotifyDescriptorExtBean.param}" 
                            		styleClass="input" 
                            		rendered="#{NotifyDescriptorExtBean.visibleParam}"> 
	                            </h:inputText>
                            </td>
                        </tr>
                        <tr>
                    </table>
                </div>
                                
				<h:inputText value="IE-Dummy" style="display:none" rendered="#{NotifyDescriptorExtBean.visibleParam}"/>

                <div class="buttonbar">
                    <h:commandButton id="button1" value="#{NotifyDescriptorExtBean.button1Text}" action="#{NotifyDescriptorExtBean.button1ActionPerformedListener}" styleClass="commandButton"  rendered="#{NotifyDescriptorExtBean.visible1}" />
                    <h:commandButton id="button2" value="#{NotifyDescriptorExtBean.button2Text}" action="#{NotifyDescriptorExtBean.button2ActionPerformedListener}" styleClass="commandButton"  rendered="#{NotifyDescriptorExtBean.visible2}" />
                    <h:commandButton id="button3" value="#{NotifyDescriptorExtBean.button3Text}" action="#{NotifyDescriptorExtBean.button3ActionPerformedListener}" styleClass="commandButton"  rendered="#{NotifyDescriptorExtBean.visible3}" />                                        
                    <h:commandButton id="button4" value="#{NotifyDescriptorExtBean.button4Text}" action="#{NotifyDescriptorExtBean.button4ActionPerformedListener}" styleClass="commandButton"  rendered="#{NotifyDescriptorExtBean.visible4}" />
                    <h:commandButton id="button5" value="#{NotifyDescriptorExtBean.button5Text}" action="#{NotifyDescriptorExtBean.button5ActionPerformedListener}" styleClass="commandButton"  rendered="#{NotifyDescriptorExtBean.visible5}" />
                </div>
                    
            </h:form>
        </f:view> 
        <script type="text/javascript">
            
            function load() {            
                setFocus();    
            }    
            
            function setFocus() {
               	if( document.getElementById('successForm:paramTextField') != null ) {
               		document.getElementById('successForm:paramTextField').focus();
               	}
               	else {
                   	document.getElementById('successForm:button1').focus();
               	}
            }    
            
        </script>

    </body>
</html>

server.app/los.mobile/WebContent/pages/common/gui/component/NotifyDescriptorPanel.jsp
<%-- 
  Copyright (c) 2006 - 2010 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%--
The taglib directive below imports the JSTL library. If you uncomment it,
you must also add the JSTL library to the project. The Add Library... action
on Libraries node in Projects view can be used to add the JSTL 1.1 library.
--%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
        <%--    <link rel="stylesheet" type="text/css" href="pages/picking/stylesheet.css" />--%>
        <%--  <link rel="stylesheet" type="text/css" href="stylesheet.css" /> --%>
        <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    
    <f:loadBundle var="bundle" basename ="de.linogistix.mobile.res.Bundle" />
    
    <body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" onload="load()">
        <f:view>
            <f:loadBundle var="bundle" basename ="de.linogistix.mobile.res.Bundle" /> 
            
            <h:form id="successForm" styleClass="form">
                <%-- Page Title--%>
                <p id="pHeader"class="pageheader">
	                <h:outputText id="pagetitle" value="#{NotifyDescriptorBean.pageTitle}" styleClass="pagetitle"/>
	                <h:graphicImage id="logo" url="/pics/logo.gif" styleClass="logo"/>
                </p>
           <%--<p id="pForm">--%>
                <%-- Form --%>
                <%-- User (Driver) --%>   
                <div style=  padding-left:5px;>
                    <%--                <h:outputFormat id="infoMsg"  value="" styleClass="info"/> --%>
                    
                    <table width="300" border="0">
                        <tr>
                            <td width="15%"><h:graphicImage id="infoImg" url="#{NotifyDescriptorBean.icon}" /></td>
                            <td width="85%"><h:outputText id="message" value="#{NotifyDescriptorBean.message}"  styleClass="label"/></td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                   <div align="center" style="padding-top:5px" >
                                       <h:commandButton id="cancelButton" value="#{NotifyDescriptorBean.buttonText}" action="#{NotifyDescriptorBean.buttonActionPerformedListener}"  styleClass="commandButton"  />
                                   </div>
                            </td>
                        </tr>
                    </table>
                    
                    <%-- Command Buttons --%>
                    
                </div>                
            </h:form>
        </f:view>
        
        <script type="text/javascript">
            
            function load() {            
                setFocus();    
            }    
            
            function setFocus() {
                document.getElementById('successForm:cancelButton').focus();
            }    
            
        </script>
         
    </body>
</html>

server.app/los.mobile/WebContent/pages/common/gui/component/cancelOrderDialog.jsp
<%-- 
  Copyright (c) 2006 - 2010 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%--
The taglib directive below imports the JSTL library. If you uncomment it,
you must also add the JSTL library to the project. The Add Library... action
on Libraries node in Projects view can be used to add the JSTL 1.1 library.
--%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
        <%--    <link rel="stylesheet" type="text/css" href="pages/picking/stylesheet.css" />--%>
        <%--  <link rel="stylesheet" type="text/css" href="stylesheet.css" /> --%>
        <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    
    <f:loadBundle var="bundle" basename ="de.linogistix.mobile.res.Bundle" />
    
    <body>
        <f:view>
            <f:loadBundle var="bundle" basename ="de.linogistix.mobile.res.Bundle" /> 
            
            <h:form id="cancelForm" styleClass="form">
                <%-- Page Title--%>
                <p id="pHeader"class="pageheader">
	                <h:outputText id="pagetitle" value="#{bundle.Picking_canceled}" styleClass="pagetitle"/>
	                <h:graphicImage id="logo" url="/pics/logo.gif" styleClass="logo"/>
                </p>
                <p id="pForm">
                <%-- Form --%>
                <%-- User (Driver) --%>   
                <div style=  padding-left:5px;>
                    <%--                <h:outputFormat id="infoMsg"  value="" styleClass="info"/> --%>
                    
                    <table width="300" border="0">
                        <tr>
                            <td width="15%"><h:graphicImage id="infoImg" url="/pics/warning.gif" /></td>
                            <td width="85%"><h:outputText id="message" value="#{bundle.PICKING_CANCEL_MESSAGE}" styleClass="label"/></td>
                        </tr>
                        <tr>
                            <td colspan="2"><form name="form1" method="post" action="">
                                <div align="center" style="padding-top:5px" >
                                    <h:commandButton id="cancelButton" value="#{bundle.Ok}" action="#{PickingBean.cancelPickingCanelDialogActionPerformedListener}" styleClass="commandButton"  />
                                </div>
                            </td>
                        </tr>
                    </table>
                    
                    <%-- Command Buttons --%>
                    
                </div>                
            </h:form>
        </f:view> 
    </body>
</html>

server.app/los.mobile/WebContent/pages/common/gui/component/differenceAmountDialog.jsp
<%-- 
  Copyright (c) 2006 - 2010 LinogistiX GmbH

  www.linogistix.com
  
  Project: myWMS-LOS
--%>

<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%--
The taglib directive below imports the JSTL library. If you uncomment it,
you must also add the JSTL library to the project. The Add Library... action
on Libraries node in Projects view can be used to add the JSTL 1.1 library.
--%>
<%@ taglib prefix="f" uri="http://java.sun.com/jsf/core" %>
<%@ taglib prefix="h" uri="http://java.sun.com/jsf/html" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>LOS</title>
        <%--    <link rel="stylesheet" type="text/css" href="pages/picking/stylesheet.css" />--%>
        <%--  <link rel="stylesheet" type="text/css" href="stylesheet.css" /> --%>
        <link rel="stylesheet" href="<%=request.getContextPath()%>/pages/stylesheet.css" type="text/css" />
    </head>
    
    <f:loadBundle var="bundle" basename ="de.linogistix.mobile.res.Bundle" />
    
    <body>
        <f:view>
            <f:loadBundle var="bundle" basename ="de.linogistix.mobile.res.Bundle" /> 
            
            <h:form id="cancelForm" styleClass="form">
                <%-- Page Title--%>
                <p id="pHeader"class="pageheader">
	                <h:outputText id="pagetitle" value="#{bundle.DIFFERENCE_AMOUNT}" styleClass="pagetitle"/>
	                <h:graphicImage id="logo" url="/pics/logo.gif" styleClass="logo"/>
                </p>
                <p id="pForm">
                <%-- Form --%>
                <%-- User (Driver) --%>   
                <div style=  padding-left:5px;>
                    <%--                <h:outputFormat id="infoMsg"  value="" styleClass="info"/> --%>
                    
                    <table width="500" border="0">
                        <tr>
                            <td width="40"><h:graphicImage id="infoImg" url="/pics/error.gif" /></td>
                            <td width="450"><h:outputText id="message" value="#{bundle.DIFFERENCE_AMOUNT_MESSAGE}" escape="false" styleClass="label"/></td>
                        </tr>
                        <tr>
                            <td colspan="2"><form name="form1" method="post" action="">
                                    <div align="center" style="padding-top:5px" >
                                        <h:commandButton id="forwardButton" value="#{bundle.TO_CONTINUE}" action="#{PickingBean.forwardDifferenceAmountDialogActionPerformedListener}" styleClass="commandButton"  />
                                        <h:commandButton id="correctButton" value="#{bundle.CORRECT_AMOUNT}" action="#{PickingBean.correctDifferenceAmountDialogActionPerformedListener}" styleClass="commandButton"  />
                                        <h:commandButton id="nullpointerButton" value="#{bundle.UNEXPECTED_NULLPOINTER_TRANSIT}" action="#{PickingBean.nullpointerDifferenceAmountDialogActionPerformedListener}" styleClass="commandButton"  />
                                    </div>
                            </td>
                        </tr>
                    </table>
                    
                    <%-- Command Buttons --%>
                    
                </div>                
            </h:form>
        </f:view> 
    </body>
</html>